name: Develop

on:
  push:
    branches:
      - develop  
jobs:
  linux_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@e1a55de

      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Deploy Docker (bitcoinnano/btco-env)
        run: ci/actions/linux/deploy-docker.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}